version: '3'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
