# Generated by Django 4.2.5 on 2023-09-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("thumbnail_size", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="my_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.accounttier",
            ),
        ),
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
