# Generated by Django 4.2.5 on 2023-09-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_accounttier_alter_customuser_my_model_delete_mymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttier",
            name="thumbnail_size",
            field=models.JSONField(default=[]),
        ),
    ]
