# Generated by Django 4.2.5 on 2023-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_accounttier_thumbnail_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttier",
            name="thumbnail_size",
            field=models.JSONField(),
        ),
    ]
