# Generated by Django 4.2.5 on 2023-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_accounttier_thumbnail_size_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnail_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
