# Generated by Django 4.2.5 on 2023-09-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_image_image_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thumbnail",
            name="height",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="width",
            field=models.IntegerField(),
        ),
    ]
