# Generated by Django 4.2.5 on 2023-09-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_thumbnail_height_alter_thumbnail_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="original",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.image",
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="image",
            field=models.ImageField(upload_to="images/thumbnails/"),
        ),
    ]
