# Generated by Django 4.2.5 on 2023-09-28 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_thumbnail_original_alter_thumbnail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttier",
            name="original_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
