# Generated by Django 4.2.5 on 2023-10-03 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_accounttier_expiring_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file_path",
                    models.FilePathField(path="media/thumbnails/", recursive=True),
                ),
                ("expiration_time", models.DateTimeField()),
            ],
        ),
    ]
