# Generated by Django 4.2.5 on 2023-10-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_expiringlink_file_path_expiringlink_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expiringlink",
            name="image_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expiring_links",
                to="api.image",
            ),
        ),
    ]
